/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.weapons;

import Business.Enterprise.Enterprise;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sneha
 */
public class WaWeaponsJPanel extends javax.swing.JPanel {
    
    private JPanel container;
    private Enterprise enterprise;
    JPanel userProcessContainer;
    /**
     * Creates new form WaWeaponsJPanel
     */
    public WaWeaponsJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this. enterprise = enterprise;
        LoadWeaponRequest();
    }

    public WaWeaponsJPanel(String userName) {
       
       initComponents();
LoadWeaponRequest();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AcceptJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        declineJButton = new javax.swing.JButton();
        acceptallJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        waJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        waJTable1 = new javax.swing.JTable();
        acceptallJButton1 = new javax.swing.JButton();
        declineJButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AcceptJButton1 = new javax.swing.JButton();

        AcceptJButton.setBackground(new java.awt.Color(153, 153, 153));
        AcceptJButton.setText("Accept");
        AcceptJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        declineJButton.setText("Decline");
        declineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineJButtonActionPerformed(evt);
            }
        });

        acceptallJButton.setText("AcceptAll");
        acceptallJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptallJButtonActionPerformed(evt);
            }
        });

        waJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Status", "Item", "quantity", "user"
            }
        ));
        jScrollPane1.setViewportView(waJTable);

        jLabel1.setText("Permission for Weapons ");

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Permission for Weapons ");

        waJTable1.setBackground(new java.awt.Color(204, 204, 0));
        waJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Status", "Item", "quantity", "user"
            }
        ));
        jScrollPane2.setViewportView(waJTable1);

        acceptallJButton1.setBackground(new java.awt.Color(204, 204, 0));
        acceptallJButton1.setText("AcceptAll");
        acceptallJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptallJButton1ActionPerformed(evt);
            }
        });

        declineJButton1.setBackground(new java.awt.Color(204, 204, 0));
        declineJButton1.setText("Decline");
        declineJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineJButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AcceptJButton1.setBackground(new java.awt.Color(204, 204, 0));
        AcceptJButton1.setText("Accept");
        AcceptJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton2)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(acceptallJButton1)
                                .addGap(91, 91, 91)
                                .addComponent(declineJButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AcceptJButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptallJButton1)
                    .addComponent(declineJButton1)
                    .addComponent(AcceptJButton1))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acceptallJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptallJButtonActionPerformed
        // TODO add your handling code here:
         
        String u_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";
        //String u1_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";//Maintain all data in one table
        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(u_query);
            //st.executeUpdate(u1_query);
            conn.close();
            LoadWeaponRequest();
        }
        catch(Exception e){
            System.out.println("Error"+e);
        }
        
    }//GEN-LAST:event_acceptallJButtonActionPerformed

    private void declineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineJButtonActionPerformed
        // TODO add your handling code here:
        int count=waJTable.getSelectedRowCount();
        if(count==0){
            JOptionPane.showMessageDialog(null, "InvalidRow Selection");
            return;
        }
        String req_id = waJTable.getValueAt(waJTable.getSelectedRow(), 0).toString();
        System.out.println(req_id);
        String u_query = "update Request_Maintenance set Status = \"Declined\" where req_id = "+req_id+"";
       
        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(u_query);
            //st.executeUpdate(u1_query);
            conn.close();
            LoadWeaponRequest();
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_declineJButtonActionPerformed

    private void AcceptJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptJButtonActionPerformed
        int count=waJTable.getSelectedRowCount();
        if(count==0){
            JOptionPane.showMessageDialog(null, "InvalidRow Selection");
            return;
        }
        String req_id = waJTable.getValueAt(waJTable.getSelectedRow(), 0).toString();
        System.out.println(req_id);
        String u_query = "update Request_Maintenance set Status = \"Accepted\" where req_id = "+req_id+"";
        
//String u1_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";//Maintain all data in one table
DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
    Statement st = conn.createStatement();
    st.executeUpdate(u_query);
    //st.executeUpdate(u1_query);
    conn.close();
    LoadWeaponRequest();
}
catch(Exception e){
    System.out.println("Error");
}// TODO add your handling code here:
    }//GEN-LAST:event_AcceptJButtonActionPerformed

    private void acceptallJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptallJButton1ActionPerformed
        // TODO add your handling code here:

        String u_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";
        //String u1_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";//Maintain all data in one table
        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(u_query);
            //st.executeUpdate(u1_query);
            conn.close();
            LoadWeaponRequest();
        }
        catch(Exception e){
            System.out.println("Error"+e);
        }
    }//GEN-LAST:event_acceptallJButton1ActionPerformed

    private void declineJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineJButton1ActionPerformed
        // TODO add your handling code here:
        int count=waJTable.getSelectedRowCount();
        if(count==0){
            JOptionPane.showMessageDialog(null, "InvalidRow Selection");
            return;
        }
        String req_id = waJTable.getValueAt(waJTable.getSelectedRow(), 0).toString();
        System.out.println(req_id);
        String u_query = "update Request_Maintenance set Status = \"Declined\" where req_id = "+req_id+"";

        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(u_query);
            //st.executeUpdate(u1_query);
            conn.close();
            LoadWeaponRequest();
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_declineJButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AcceptJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptJButton1ActionPerformed
        int count=waJTable.getSelectedRowCount();
        if(count==0){
            JOptionPane.showMessageDialog(null, "InvalidRow Selection");
            return;
        }
        String req_id = waJTable.getValueAt(waJTable.getSelectedRow(), 0).toString();
        System.out.println(req_id);
        String u_query = "update Request_Maintenance set Status = \"Accepted\" where req_id = "+req_id+"";

        //String u1_query = "update Request_Maintenance set Status = \"Accepted\" where Status = \"Active\"";//Maintain all data in one table
        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(u_query);
            //st.executeUpdate(u1_query);
            conn.close();
            LoadWeaponRequest();
        }
        catch(Exception e){
            System.out.println("Error");
        }// TODO add your handling code here:
    }//GEN-LAST:event_AcceptJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptJButton;
    private javax.swing.JButton AcceptJButton1;
    private javax.swing.JButton acceptallJButton;
    private javax.swing.JButton acceptallJButton1;
    private javax.swing.JButton declineJButton;
    private javax.swing.JButton declineJButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable waJTable;
    private javax.swing.JTable waJTable1;
    // End of variables declaration//GEN-END:variables

    private void LoadWeaponRequest() {
         String query = "select * from Request_Maintenance";
        DefaultTableModel model = (DefaultTableModel) waJTable.getModel();
        model.setRowCount(0);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                Object[] row = new Object[5];
                row[0] = rs.getInt("req_id");
                row[1] = rs.getString("Status");
                row[2] = rs.getString("Name");
                row[3] = rs.getString("quantity");
                row[4] = rs.getString("user");
                model.addRow(row);
            }
            rs.close();
            conn.close();
        }
        catch(Exception e){
            System.out.println("Error");
        } //To change body of generated methods, choose Tools | Templates.
    }
}
