/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PositionWorkArea;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.sql.*;
import userinterface.CheckingStatus.*;
/**
 *
 * @author Sneha
 */
public class HeadJPanel extends javax.swing.JPanel {
    
    private JPanel container;
    private Enterprise enterprise;
    /**
     * Creates new form HeadJPanel
     */
    public HeadJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this. enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        govtJButton = new javax.swing.JButton();
        warPermissionJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        waRequestJButton = new javax.swing.JButton();
        govstatus = new javax.swing.JButton();
        wastatus = new javax.swing.JButton();
        warstatus = new javax.swing.JButton();
        govlabel = new javax.swing.JLabel();
        warlabel = new javax.swing.JLabel();
        WAlabel = new javax.swing.JLabel();
        soldierWeaponRequestJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose your action");

        govtJButton.setBackground(new java.awt.Color(204, 204, 0));
        govtJButton.setText("Request permission for weapons from the Government");
        govtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govtJButtonActionPerformed(evt);
            }
        });

        warPermissionJButton.setBackground(new java.awt.Color(204, 204, 0));
        warPermissionJButton.setText("Request permission from Governemnt for War");
        warPermissionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warPermissionJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(204, 204, 0));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        waRequestJButton.setBackground(new java.awt.Color(204, 204, 0));
        waRequestJButton.setText("Request permission for weapons from the Weapons Authorizer");
        waRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waRequestJButtonActionPerformed(evt);
            }
        });

        govstatus.setBackground(new java.awt.Color(204, 204, 0));
        govstatus.setText("Check Weapon Status (Govt)");
        govstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govstatusActionPerformed(evt);
            }
        });

        wastatus.setBackground(new java.awt.Color(204, 204, 0));
        wastatus.setText("Check Weapon Status (WA)");
        wastatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wastatusActionPerformed(evt);
            }
        });

        warstatus.setBackground(new java.awt.Color(204, 204, 0));
        warstatus.setText("Check War Status");
        warstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warstatusActionPerformed(evt);
            }
        });

        soldierWeaponRequestJButton.setBackground(new java.awt.Color(204, 204, 0));
        soldierWeaponRequestJButton.setText("Check Request from soldier");
        soldierWeaponRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldierWeaponRequestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(govlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(warlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(WAlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(govstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soldierWeaponRequestJButton)
                            .addComponent(wastatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waRequestJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warPermissionJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(govtJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backJButton)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(backJButton)
                .addGap(26, 26, 26)
                .addComponent(govtJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(govlabel)
                .addGap(16, 16, 16)
                .addComponent(warPermissionJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warlabel)
                .addGap(11, 11, 11)
                .addComponent(waRequestJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WAlabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(govstatus)
                    .addComponent(wastatus))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soldierWeaponRequestJButton)
                    .addComponent(warstatus))
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void govstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govstatusActionPerformed
                // TODO add your handling code here:
        CheckWeaponStatusGovtJPanel train = new CheckWeaponStatusGovtJPanel(container, enterprise);
        container.add("CheckWeaponStatusGovtJPanel",train);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_govstatusActionPerformed

    private void govtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govtJButtonActionPerformed
        // TODO add your handling code here:
        long pid = (long)(Math.random() * 100000);
        govlabel.setText("Your permission id is "+ pid);
        String query = "insert into govw_perm_id values("+pid+", \"Active\")";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(query);
            conn.close();
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_govtJButtonActionPerformed

    private void warPermissionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warPermissionJButtonActionPerformed
        // TODO add your handling code here:
        long pid = (long)(Math.random() * 10000000);
        warlabel.setText("Your permission id is "+ pid);
        
        String query = "insert into perm_id values("+pid+", \"Active\")";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(query);
            conn.close();
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_warPermissionJButtonActionPerformed

    private void waRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waRequestJButtonActionPerformed
        // TODO add your handling code here:
        long pid = (long)(Math.random() * 100000);
        WAlabel.setText("Your permission id is "+ pid);
        String query = "insert into waw_perm_id values("+pid+", \"Active\")";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys","root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(query);
            conn.close();
        }
        catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_waRequestJButtonActionPerformed

    private void wastatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wastatusActionPerformed
        // TODO add your handling code here:
        CheckWeaponStatusWAJPanel train = new CheckWeaponStatusWAJPanel(container, enterprise);
        container.add("CheckWeaponStatusWAJPanel",train);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_wastatusActionPerformed

    private void warstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warstatusActionPerformed
        // TODO add your handling code here:
        CheckWarStatusJPanel train = new CheckWarStatusJPanel(container, enterprise);
        container.add("CheckWarStatusJPanel",train);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_warstatusActionPerformed

    private void soldierWeaponRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldierWeaponRequestJButtonActionPerformed
        // TODO add your handling code here:
        SoldierWeaponRequestJPanel train = new SoldierWeaponRequestJPanel(container, enterprise);
        container.add("SoldierWeaponRequestJPanel",train);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_soldierWeaponRequestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WAlabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel govlabel;
    private javax.swing.JButton govstatus;
    private javax.swing.JButton govtJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton soldierWeaponRequestJButton;
    private javax.swing.JButton waRequestJButton;
    private javax.swing.JButton warPermissionJButton;
    private javax.swing.JLabel warlabel;
    private javax.swing.JButton warstatus;
    private javax.swing.JButton wastatus;
    // End of variables declaration//GEN-END:variables
}
