/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PositionWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorAppointment.AppointmentStatus;

/**
 *
 * @author Sneha
 */
public class SoldierDisplayJPanel extends javax.swing.JPanel {

    private JPanel container;
    private JPanel containerflow = null;
    Enterprise enterprise;
    JPanel userProcessContainer;
    EcoSystem system;
    String user;

    /**
     * Creates new form SoldierJPanel
     */
    public SoldierDisplayJPanel(JPanel container, Enterprise enterprise, String user) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.user = user;
        loadSoldierDetails();

        checkwarflag();
    }

    public SoldierDisplayJPanel(String userName, JPanel containerflow) {
        initComponents();
        this.user = userName;
        this.containerflow = containerflow;
        loadSoldierDetails();
        System.out.print(userName);
checkwarflag();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        dobTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        trainerNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        weaponRequestJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dateOfJoiningJTextField = new javax.swing.JTextField();
        gendertextfield = new javax.swing.JTextField();
        benefittextfield = new javax.swing.JTextField();
        phonelabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        permidlabel = new javax.swing.JLabel();
        scheduleAppointmentJButton1 = new javax.swing.JButton();
        appstatbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        appointmentlabel = new javax.swing.JLabel();
        emergencyjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soldier Account");

        jLabel2.setText("Name");

        jLabel3.setText("Date of birth");

        jLabel4.setText("Gender");

        jLabel5.setText("Address");

        jLabel6.setText("ID");

        addressTextArea.setEditable(false);
        addressTextArea.setBackground(new java.awt.Color(204, 204, 0));
        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        dobTextField.setEditable(false);
        dobTextField.setBackground(new java.awt.Color(204, 204, 0));

        idTextField.setEditable(false);
        idTextField.setBackground(new java.awt.Color(204, 204, 0));

        nameTextField.setEditable(false);
        nameTextField.setBackground(new java.awt.Color(204, 204, 0));

        phoneTextField.setEditable(false);
        phoneTextField.setBackground(new java.awt.Color(204, 204, 0));

        jLabel8.setText("Name of the trainer");

        trainerNameTextField.setEditable(false);
        trainerNameTextField.setBackground(new java.awt.Color(204, 204, 0));

        jLabel10.setText("Benefits");

        backJButton.setBackground(new java.awt.Color(204, 204, 0));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        weaponRequestJButton.setBackground(new java.awt.Color(204, 204, 0));
        weaponRequestJButton.setText("Request for Weapon");
        weaponRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponRequestJButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Date of Joining");

        dateOfJoiningJTextField.setEditable(false);
        dateOfJoiningJTextField.setBackground(new java.awt.Color(204, 204, 0));

        gendertextfield.setEditable(false);
        gendertextfield.setBackground(new java.awt.Color(204, 204, 0));

        benefittextfield.setEditable(false);
        benefittextfield.setBackground(new java.awt.Color(204, 204, 0));

        phonelabel.setText("Phone");

        scheduleAppointmentJButton1.setBackground(new java.awt.Color(204, 204, 0));
        scheduleAppointmentJButton1.setText("Schedule Doctor Appointment");
        scheduleAppointmentJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleAppointmentJButton1ActionPerformed(evt);
            }
        });

        appstatbtn.setBackground(new java.awt.Color(204, 204, 0));
        appstatbtn.setText("Check Appointment Status");
        appstatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appstatbtnActionPerformed(evt);
            }
        });

        appointmentlabel.setText("<Appointment Number>");

        emergencyjLabel.setText("    peace");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phonelabel)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(weaponRequestJButton)
                                .addComponent(appstatbtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(benefittextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scheduleAppointmentJButton1)
                            .addComponent(appointmentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateOfJoiningJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gendertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                                .addComponent(emergencyjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(permidlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backJButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(emergencyjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfJoiningJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gendertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permidlabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(trainerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(benefittextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleAppointmentJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appstatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(appointmentlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void weaponRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponRequestJButtonActionPerformed

        System.out.print(user);
        SpecificWeaponJPanel hp = new SpecificWeaponJPanel(user, containerflow);
        containerflow.removeAll();
        containerflow.add("SpecificWeaponJPanel", hp);
        CardLayout crdLyt = (CardLayout) containerflow.getLayout();
        crdLyt.next(containerflow);


    }//GEN-LAST:event_weaponRequestJButtonActionPerformed

    private void loadSoldierDetails() {
        String query = "select * from soldier_details where username = \"" + user + "\"";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys", "root", "");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String name = rs.getString("Name");
                nameTextField.setText(name);

                String ID = rs.getString("ID");
                idTextField.setText(ID);

                String dob = rs.getDate("DOB").toString();
                dobTextField.setText(dob);

                String doj = rs.getDate("DOJ").toString();
                dateOfJoiningJTextField.setText(doj);

                String gender = rs.getString("Gender");
                gendertextfield.setText(gender);

                String address = rs.getString("Address");
                addressTextArea.setText(address);

                int phone = rs.getInt("Phone");
                phoneTextField.setText(Integer.toString(phone));

                String sol = rs.getString("trainer_name");
                trainerNameTextField.setText(sol);

                String ben = rs.getString("Benefits");
                benefittextfield.setText(ben);
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            System.out.println("Error");
        }
    }
    private void scheduleAppointmentJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleAppointmentJButton1ActionPerformed
        // TODO add your handling code here:
        int app_id = (int) (Math.random() * 100);
        appointmentlabel.setText("Your Appointment ID is " + app_id);

        String query = "insert into doc_app(req_id,Status,Position) values(" + app_id + ",\"Pending\",\"name\")";
        System.out.println(query);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys", "root", "");
            Statement st = conn.createStatement();
            st.executeUpdate(query);
            jLabel1.setText("Sucessfully Added");
            conn.close();
            loadSoldierDetails();
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
    }//GEN-LAST:event_scheduleAppointmentJButton1ActionPerformed

    private void appstatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appstatbtnActionPerformed
        // TODO add your handling code here:
        String poc = appointmentlabel.getText();
        if (null != poc && !poc.equalsIgnoreCase("")) {

            AppointmentStatus ap = new AppointmentStatus(user);

            containerflow.removeAll();
            containerflow.add("AppointmentStatus", ap);
            CardLayout crdLyt = (CardLayout) containerflow.getLayout();
            crdLyt.next(containerflow);
        } else {
            JOptionPane.showMessageDialog(null, "Appointment ID is null");
        }
    }//GEN-LAST:event_appstatbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel appointmentlabel;
    private javax.swing.JButton appstatbtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField benefittextfield;
    private javax.swing.JTextField dateOfJoiningJTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel emergencyjLabel;
    private javax.swing.JTextField gendertextfield;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel permidlabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JButton scheduleAppointmentJButton1;
    private javax.swing.JTextField trainerNameTextField;
    private javax.swing.JButton weaponRequestJButton;
    // End of variables declaration//GEN-END:variables

    private void checkwarflag() {
        String query = "select * from Request_Maintenance";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sys", "root", "");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            String Status;
            while (rs.next()) {

                Status = rs.getString("Status");
                System.out.println("testing color");
                if (Status.equalsIgnoreCase("ACCEPTED")) {
                    emergencyjLabel.setText("UNDER WAR");
                    emergencyjLabel.setBackground(Color.red);
                    emergencyjLabel.setOpaque(true);
                    break;
                }
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            System.out.println("Error");
        } //To change body of generated methods, choose Tools | Templates.
    }
}
