/*
 * WorldArmedForcesJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class WorldArmedForcesJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    
    /** Creates new form AdminWorkAreaJPanel */
    public WorldArmedForcesJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        continentsjComboBox = new javax.swing.JComboBox<>();
        submitJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("World Armed Forces Organisation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, -1));

        continentsjComboBox.setBackground(new java.awt.Color(204, 204, 0));
        continentsjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Continent", "North America", "South America", "Asia", "Europe", "Australia", "Africa" }));
        continentsjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continentsjComboBoxActionPerformed(evt);
            }
        });
        add(continentsjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, -1));

        submitJButton.setBackground(new java.awt.Color(204, 204, 0));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        String cont = (String)continentsjComboBox.getSelectedItem();
        UserDetailIO udio = new UserDetailIO();
        udio.setContinent(cont);
        if(cont.equals("North America")){
            NorthAmericaJPanel weapon = new NorthAmericaJPanel(userProcessContainer, enterprise,udio);
            userProcessContainer.add("NorthAmericaJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else if(cont.equals("South America")){
            SouthAmericaJPanel weapon = new SouthAmericaJPanel(userProcessContainer, enterprise);
            userProcessContainer.add("SouthAmericaJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else if(cont.equals("Africa")){
            AfricaJPanel weapon = new AfricaJPanel(userProcessContainer, enterprise);
            userProcessContainer.add("AfricaJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else if(cont.equals("Asia")){
            AsiaJPanel weapon = new AsiaJPanel(userProcessContainer, enterprise);
            userProcessContainer.add("AsiaJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else if(cont.equals("Australia")){
            AustraliaJPanel weapon = new AustraliaJPanel(userProcessContainer, enterprise);
            userProcessContainer.add("AustraliaJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else if(cont.equals("Europe")){
            EuropeJPanel weapon = new EuropeJPanel(userProcessContainer, enterprise);
            userProcessContainer.add("EuropeJPanel", weapon);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else{
            
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void continentsjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continentsjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continentsjComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> continentsjComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
